repos:
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.2 
    hooks:
      - id: snakefmt
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks:
      - id: style-files
        args: [--warn_only]
      - id: parsable-R  
        args: [--warn-only]
      - id: lintr
        args: [--warn_only]
        verbose: true  

